/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package physicslab;

import javax.swing.JFrame;

/**
 *
 * @author Jowen
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Usua1 = new javax.swing.JTextField();
        pass1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        BotRegistar = new javax.swing.JButton();
        jLabelRegistro1 = new javax.swing.JLabel();
        Usua2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Usua3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pass2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(137, 196, 244));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registro De Usuario");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel5)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        jPanel6.setBackground(new java.awt.Color(44, 62, 80));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 240, 241));
        jLabel7.setText("Contraseña:");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 173, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8.setText("Usuario:");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 131, -1, -1));

        Usua1.setBackground(new java.awt.Color(108, 122, 137));
        Usua1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Usua1.setForeground(new java.awt.Color(228, 241, 254));
        Usua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usua1ActionPerformed(evt);
            }
        });
        jPanel6.add(Usua1, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 132, 225, -1));

        pass1.setBackground(new java.awt.Color(108, 122, 137));
        pass1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pass1.setForeground(new java.awt.Color(228, 241, 254));
        jPanel6.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 174, 225, -1));

        jButton3.setBackground(new java.awt.Color(192, 57, 43));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 271, 95, 37));

        BotRegistar.setBackground(new java.awt.Color(34, 167, 240));
        BotRegistar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotRegistar.setForeground(new java.awt.Color(255, 255, 255));
        BotRegistar.setText("Registrar");
        BotRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotRegistarActionPerformed(evt);
            }
        });
        jPanel6.add(BotRegistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 271, -1, 37));

        jLabelRegistro1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistro1.setText("                                  Clic aqui para hacer Log In");
        jLabelRegistro1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegistro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegistro1MouseClicked(evt);
            }
        });
        jPanel6.add(jLabelRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 337, 344, -1));

        Usua2.setBackground(new java.awt.Color(108, 122, 137));
        Usua2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Usua2.setForeground(new java.awt.Color(228, 241, 254));
        Usua2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usua2ActionPerformed(evt);
            }
        });
        jPanel6.add(Usua2, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 48, 225, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 240, 241));
        jLabel9.setText("Nombre:");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 47, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(236, 240, 241));
        jLabel10.setText("Apellido:");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 89, -1, -1));

        Usua3.setBackground(new java.awt.Color(108, 122, 137));
        Usua3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Usua3.setForeground(new java.awt.Color(228, 241, 254));
        Usua3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usua3ActionPerformed(evt);
            }
        });
        jPanel6.add(Usua3, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 90, 225, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(236, 240, 241));
        jLabel11.setText("Confirmar:");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 215, -1, -1));

        pass2.setBackground(new java.awt.Color(108, 122, 137));
        pass2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pass2.setForeground(new java.awt.Color(228, 241, 254));
        jPanel6.add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 216, 225, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 410, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Usua3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usua3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Usua3ActionPerformed

    private void Usua2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usua2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Usua2ActionPerformed

    private void jLabelRegistro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistro1MouseClicked
        Login Log = new Login();
       Log.setVisible(true);
       Log.pack();
       Log.setLocationRelativeTo(null);
       Log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
    }//GEN-LAST:event_jLabelRegistro1MouseClicked

    private void BotRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotRegistarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotRegistarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Usua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usua1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Usua1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotRegistar;
    private javax.swing.JTextField Usua1;
    private javax.swing.JTextField Usua2;
    private javax.swing.JTextField Usua3;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelRegistro1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    // End of variables declaration//GEN-END:variables
}
