/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package physicslab;

import Exceptions.ValidacionRes;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jowen
 */
public class VenEjercicio extends javax.swing.JFrame {
    Integer error=1;
    Integer auxiliar =100;
    Integer puntaje=0;
    public VenEjercicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        ImageIcon Img_Mov;
        Img_Mov = new ImageIcon(getClass().getResource("/Imagenes/Movimiento.png"));
        Icon Icono_Mov = new ImageIcon(Img_Mov.getImage().getScaledInstance(LabelImagen.getWidth(),LabelImagen.getHeight(), Image.SCALE_DEFAULT)); 
        LabelImagen.setIcon(Icono_Mov);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelImagen = new javax.swing.JLabel();
        ButtonMovimiento = new javax.swing.JButton();
        ButtonDetenerM = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ResVelocidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ResTiempo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ResDistancia = new javax.swing.JTextField();
        ButtonAyuda = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ButtonCalculadora = new javax.swing.JButton();
        ButtonRespuesta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(70, 70, 121));

        LabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Movimiento.png"))); // NOI18N

        ButtonMovimiento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonMovimiento.setText("Iniciar movimiento");
        ButtonMovimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMovimientoActionPerformed(evt);
            }
        });

        ButtonDetenerM.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonDetenerM.setText("Detener movimiento");
        ButtonDetenerM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonDetenerM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDetenerMActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setText("   Velocidad:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setText("Tiempo:");

        ResTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResTiempoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel3.setText("Distancia:");

        ResDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResDistanciaActionPerformed(evt);
            }
        });

        ButtonAyuda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonAyuda.setText("Ayuda?");
        ButtonAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAyudaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel4.setText("EJERCICIO");

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\n\nCalcular la velocidad \nde un vehiculo que se \ndesplaza (100) metros \nen (5) segundos.\n\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        ButtonCalculadora.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonCalculadora.setText("Calculadora");
        ButtonCalculadora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalculadoraActionPerformed(evt);
            }
        });

        ButtonRespuesta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonRespuesta.setText("Guardar solucion");
        ButtonRespuesta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRespuestaActionPerformed(evt);
            }
        });

        jLabel5.setText("(m)");

        jLabel6.setText("(s)");

        jLabel7.setText("(m/s)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonMovimiento)
                        .addGap(76, 76, 76)
                        .addComponent(ButtonDetenerM)
                        .addGap(76, 76, 76)
                        .addComponent(ButtonAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(ButtonCalculadora)
                        .addGap(110, 110, 110))
                    .addComponent(LabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ResDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ResVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(ResTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonRespuesta)
                        .addGap(78, 78, 78))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ResVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ResTiempo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ResDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonMovimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonDetenerM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtonRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDetenerMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDetenerMActionPerformed
        ImageIcon Img_Mov;
        Img_Mov = new ImageIcon(getClass().getResource("/Imagenes/Movimiento.png"));
        Icon Icono_Mov = new ImageIcon(Img_Mov.getImage().getScaledInstance(LabelImagen.getWidth(),LabelImagen.getHeight(), Image.SCALE_DEFAULT)); 
        LabelImagen.setIcon(Icono_Mov);
    }//GEN-LAST:event_ButtonDetenerMActionPerformed

    private void ButtonMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMovimientoActionPerformed
       ImageIcon Img_Mov;
       Img_Mov = new ImageIcon(getClass().getResource("/Imagenes/GifM.gif"));
       Icon Icono_Mov = new ImageIcon(Img_Mov.getImage().getScaledInstance(LabelImagen.getWidth(),LabelImagen.getHeight(), Image.SCALE_DEFAULT)); 
       LabelImagen.setIcon(Icono_Mov);
    }//GEN-LAST:event_ButtonMovimientoActionPerformed

    private void ResTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResTiempoActionPerformed

    private void ResDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResDistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResDistanciaActionPerformed

    private void ButtonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAyudaActionPerformed
        JOptionPane.showMessageDialog(this, "Formulas\n"
                + "V = desplazamiento(/)tiempo\n"
                + "-------------------------------------------\n"
                + "V = distancia recorrida(/)tiempo(rapidez)\n"
                + "-------------------------------------------\n"
                + "D = velocidad(*)tiempo\n"
                + "-------------------------------------------\n"
                + "T = distancia(/)velocidad\n"
                + "-------------------------------------------");
    }//GEN-LAST:event_ButtonAyudaActionPerformed

    private void ButtonCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalculadoraActionPerformed
           VenCalculadora ventana = new VenCalculadora();
            ventana.setVisible(true);
    }//GEN-LAST:event_ButtonCalculadoraActionPerformed

    private void ButtonRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRespuestaActionPerformed
        
       if(Float.parseFloat(ResVelocidad.getText())==20){
           
           
           puntaje= auxiliar;
          JOptionPane.showMessageDialog(null, "respuesta correcta,tu puntaje es: ("+auxiliar+ ")"); 
          
          VenEjercicio2 ventana = new VenEjercicio2();
          ventana.setVisible(true); 
          this.dispose();
          
        
          
        }else{
           puntaje= auxiliar;
           JOptionPane.showMessageDialog(null, "respuesta incorrecta*");
           
            auxiliar = 100 -error*10 ;
           error ++;
        }
   
    }//GEN-LAST:event_ButtonRespuestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VenEjercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VenEjercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VenEjercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VenEjercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VenEjercicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAyuda;
    private javax.swing.JButton ButtonCalculadora;
    private javax.swing.JButton ButtonDetenerM;
    private javax.swing.JButton ButtonMovimiento;
    private javax.swing.JButton ButtonRespuesta;
    private javax.swing.JLabel LabelImagen;
    private javax.swing.JTextField ResDistancia;
    private javax.swing.JTextField ResTiempo;
    private javax.swing.JTextField ResVelocidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
